# Generated by Django 3.0.5 on 2021-06-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdeQuartos', models.IntegerField()),
                ('qtdeSuites', models.IntegerField()),
                ('qtdeSalaEstar', models.IntegerField()),
                ('qtdeSalaJantar', models.IntegerField()),
                ('qtdeVagasGaragem', models.IntegerField()),
                ('area', models.IntegerField()),
                ('possuiArmarioEmbutido', models.BooleanField()),
                ('descricao', models.TextField()),
                ('andar', models.IntegerField()),
                ('valorCondominio', models.FloatField()),
                ('possuiPortaria', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdeQuartos', models.IntegerField()),
                ('qtdeSuites', models.IntegerField()),
                ('qtdeSalaEstar', models.IntegerField()),
                ('qtdeVagasGaragem', models.IntegerField()),
                ('area', models.IntegerField()),
                ('possuiArmarioEmbutido', models.BooleanField()),
                ('descricao', models.TextField()),
            ],
        ),
    ]
