# Generated by Django 3.0.5 on 2021-06-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casa',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
    ]
