# Generated by Django 3.0.5 on 2021-06-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20210626_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='aluguel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casa',
            name='aluguel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
