# Generated by Django 3.0.5 on 2021-06-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20210626_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='possuiArmarioEmbutido',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=128),
        ),
    ]
