# Generated by Django 3.0.5 on 2021-06-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20210626_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='possuiArmarioEmbutido',
            field=models.BooleanField(choices=[(True, 'sim'), (False, 'nao')]),
        ),
    ]
