# Generated by Django 3.0.5 on 2021-06-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_horariomarcado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariomarcado',
            old_name='id_imovel',
            new_name='idImovel',
        ),
        migrations.RenameField(
            model_name='horariomarcado',
            old_name='tipo_imovel',
            new_name='tipoImovel',
        ),
    ]
