# Generated by Django 3.0.5 on 2021-06-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_auto_20210628_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariomarcado',
            name='tipoImovel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
